### ISSUE TITLE
Issue with the pkl 

### ISSUE THREAD

**Issue by RonakSingh69** [skrishnan2001/IPL-Winning-Team-Predictor#1]
ValueError: node array from the pickle has an incompatible dtype: - expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64} - got : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
Traceback:
File "C:\Users\ronak\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "C:\Users\ronak\Downloads\IPL-Winning-Team-Predictor-master\IPL-Winning-Team-Predictor-master\app.py", line 23, in <module>
    Rf = pickle.load(open('Rf.pkl', 'rb'))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "sklearn\\tree\\_tree.pyx", line 865, in sklearn.tree._tree.Tree.__setstate__
File "sklearn\\tree\\_tree.pyx", line 1571, in sklearn.tree._tree._check_node_ndarr

this error pops up everytime i run it , please provide further assistance

**Comment by skrishnan2001** [comment]
I was working on this project about two years ago, and I believe the issue might be related to the version of the package installed. Given that there have likely been numerous upgrades to these dependencies over the past two years, I suggest changing the version of `scikit-learn to 1.2.2`. After doing so, please regenerate the pickle files for all three ML models by running all the cells in the ExploratoryAnalysis.ipynb notebook. I hope this resolves the issue!

**Comment by skrishnan2001** [comment]
Closing the issue as the solution has been provided in my previous comment.
